-- Data fixes that run after `prisma db push` on every deploy.
-- These are idempotent — safe to run on every deploy.
-- `db push` only syncs schema structure, not data, so migration SQL
-- files with DML (UPDATE/INSERT) are never executed by it.
--
-- IMPORTANT: Do NOT add UPDATE/DELETE statements that modify real
-- production data unconditionally. Use WHERE clauses with specific IDs
-- or guards that only apply to seed/demo data, never real company data.

-- (No data fixes needed — the destructive "Nirman Constructions" rename
-- was removed because it blanked GSTIN/PAN/address for the real
-- production company on every deploy.)
