import { chromium } from "@playwright/test";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
page.setDefaultTimeout(45000);
const reqs = [];
page.on("request", (r) => { if (r.url().includes("phone-password") || r.url().includes("passkey") || r.url().includes("webauthn")) reqs.push(`${r.method()} ${r.url().split("/").pop()}`); });
page.on("response", (r) => { if (r.url().includes("phone-password") || r.url().includes("passkey")) reqs.push(`resp:${r.status()}`); });
page.on("pageerror", (e) => reqs.push(`JS_ERR:${e.message.slice(0,80)}`));
await page.goto("https://nirman.life/sign-in", { waitUntil: "domcontentloaded" });
await page.waitForTimeout(5000);
await page.locator("input[type=tel]").fill("9412230391");
await page.locator("input[type=password]").fill("BnbpUVKamkNNWbZ9");
await page.locator("button[type=submit]").first().tap();
await page.waitForTimeout(10000);
console.log("url:", page.url());
console.log("reqs:", JSON.stringify(reqs));
const body = await page.locator("body").textContent();
console.log("page:", /Sanjeev|SRG|home|dashboard/i.exec(body)?.[0]);
await b.close();
