packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@sentry/cli': set this to true or false
  esbuild: set this to true or false
  msw: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false

minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.3'
  - '@better-auth/drizzle-adapter@1.7.3'
  - '@better-auth/kysely-adapter@1.7.3'
  - '@better-auth/memory-adapter@1.7.3'
  - '@better-auth/mongo-adapter@1.7.3'
  - '@better-auth/passkey@1.7.3'
  - '@better-auth/prisma-adapter@1.7.3'
  - '@better-auth/telemetry@1.7.3'
  - better-auth@1.7.3

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - esbuild
  - sharp
  - unrs-resolver
