import * as React from "react";
import { cn } from "@/lib/utils";

/**
 * PRINT LAYOUT — the shared A4 print page wrapper.
 *
 * Replaces the 20+ print route components that each re-implement:
 * A4 page wrapper + company header + document meta + footer + page
 * break rules. Designed for `window.print()` — all interactive UI
 * is hidden via the `print:` variant, and this layout is only visible
 * in print mode.
 *
 * Usage:
 *   <PrintLayout title="Purchase Order" meta={{ number: "PO-001", date: "2024-01-15" }}>
 *     <PrintSection title="Items">...</PrintSection>
 *     <PrintSection title="Totals">...</PrintSection>
 *   </PrintLayout>
 */
export function PrintLayout({
  title,
  subtitle,
  meta,
  company,
  children,
  className,
}: {
  title: string;
  subtitle?: string;
  meta?: { label: string; value: React.ReactNode }[];
  company?: { name: string; address?: string; phone?: string; gstin?: string };
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <div className={cn("mx-auto max-w-[800px] p-8 print:p-6", className)}>
      {/* ── Header ── */}
      <header className="flex items-start justify-between gap-4 border-b border-border pb-4">
        <div className="min-w-0">
          {company && (
            <div className="mb-1">
              <p className="text-title font-semibold text-foreground">{company.name}</p>
              {company.address && <p className="text-caption text-muted-foreground">{company.address}</p>}
              <div className="mt-0.5 flex gap-3 text-caption text-muted-foreground">
                {company.phone && <span>{company.phone}</span>}
                {company.gstin && <span>GSTIN: {company.gstin}</span>}
              </div>
            </div>
          )}
          <h1 className="text-section font-semibold text-foreground">{title}</h1>
          {subtitle && <p className="text-body text-muted-foreground">{subtitle}</p>}
        </div>
        {meta && meta.length > 0 && (
          <dl className="shrink-0 text-right">
            {meta.map((m) => (
              <div key={m.label}>
                <dt className="text-caption text-muted-foreground">{m.label}</dt>
                <dd className="text-body font-medium text-foreground">{m.value}</dd>
              </div>
            ))}
          </dl>
        )}
      </header>

      {/* ── Body ── */}
      <main className="py-4">{children}</main>

      {/* ── Footer ── */}
      <footer className="mt-8 border-t border-border pt-3 text-caption text-muted-foreground">
        <p>Generated by Nirman Inventory OS</p>
      </footer>
    </div>
  );
}

/**
 * PRINT SECTION — a titled section within a PrintLayout.
 */
export function PrintSection({
  title,
  children,
  className,
}: {
  title?: string;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <section className={cn("mb-4", className)}>
      {title && <h2 className="mb-2 text-label font-medium text-muted-foreground">{title}</h2>}
      {children}
    </section>
  );
}

/**
 * PRINT TOTALS — a right-aligned totals block for invoices/POs.
 */
export function PrintTotals({
  rows,
  className,
}: {
  rows: { label: string; value: React.ReactNode; bold?: boolean }[];
  className?: string;
}) {
  return (
    <div className={cn("ml-auto w-[260px]", className)}>
      <dl className="flex flex-col gap-1">
        {rows.map((r) => (
          <div
            key={r.label}
            className={cn(
              "flex items-center justify-between gap-4 py-1",
              r.bold && "border-t border-border-strong text-label font-semibold",
            )}
          >
            <dt className="text-body text-muted-foreground">{r.label}</dt>
            <dd className={cn("text-body tnum text-foreground", r.bold && "font-semibold")}>{r.value}</dd>
          </div>
        ))}
      </dl>
    </div>
  );
}
