import Capacitor
import UIKit

/**
 * App bridge view controller — subclasses CAPBridgeViewController solely
 * to register app-local plugins. `packageClassList` in
 * capacitor.config.json is regenerated by `cap sync` and can't hold local
 * classes, so instance registration happens here — before the remote
 * page's document-start scripts run.
 */
class AppBridgeViewController: CAPBridgeViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        bridge?.registerPluginInstance(PrintPlugin())
    }
}
