import { connection } from "next/server";
import { PrintToolbar } from "@/components/print/print-button";
import { PrintHeader } from "@/components/print/print-header";
import { prisma } from "@nirman/db";
import { toNum, getUserRole, getCompany } from "@/lib/server";
import { PERM, hasPermission } from "@/lib/roles";
import { formatCurrency, formatDate, formatNumber } from "@/lib/utils";
import { notFound } from "next/navigation";

/**
 * Print-friendly Scrap Generation Slip — for internally generated
 * material (scrap, by-products) added to stock at a scrap valuation.
 * Shows slip header, destination location, line items with qty/unit
 * cost, and total scrap value. Opened in a new tab from the scrap
 * generations list.
 */
export default async function ScrapGenerationPrintPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  await connection();
  const { id } = await params;

  const role = await getUserRole();
  if (!hasPermission(role, PERM.INVENTORY_VIEW)) {
    notFound();
  }
  const company = await getCompany();

  const scrap = await prisma.scrapGeneration.findFirst({
    where: { id, companyId: company.id },
    include: {
      toLocation: { select: { name: true } },
      project: { select: { name: true } },
      sourceMaterial: { select: { code: true, name: true } },
      lines: {
        include: {
          material: { select: { code: true, name: true, unit: true } },
        },
        orderBy: { material: { name: "asc" } },
      },
      createdBy: { select: { name: true } },
    },
  });

  if (!scrap) notFound();

  const totalValue = scrap.lines.reduce(
    (sum, l) => sum + toNum(l.qty) * toNum(l.unitCost),
    0,
  );
  const totalQty = scrap.lines.reduce((sum, l) => sum + toNum(l.qty), 0);

  return (<>
          <PrintToolbar title="Scrap Generation Slip" />
    <div className="print-page mx-auto max-w-3xl bg-white p-8 text-black print:p-4">
      <PrintHeader
        company={company}
        title="Scrap Generation Slip"
        docNumber={scrap.scrapNumber}
        date={scrap.generationDate}
      />

      {/* Slip info */}
      <div className="mt-4 grid grid-cols-2 gap-4 text-sm">
        <div className="rounded-md border border-gray-300 p-2.5">
          <div className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Destination</div>
          <div className="font-semibold">{scrap.toLocation.name}</div>
          {scrap.project && (
            <div className="text-xs text-gray-500">Project: {scrap.project.name}</div>
          )}
          {scrap.sourceMaterial && (
            <div className="text-xs text-gray-500">
              Source: {scrap.sourceMaterial.code} — {scrap.sourceMaterial.name}
            </div>
          )}
          {scrap.createdBy && (
            <div className="text-gray-600">Generated by: {scrap.createdBy.name}</div>
          )}
        </div>
      </div>

      {/* Line items table */}
      <table className="mt-4 w-full border-collapse text-sm">
        <thead>
          <tr className="border-b border-black">
            <th className="border-r border-gray-300 px-2 py-1.5 text-left font-semibold">Sr.</th>
            <th className="border-r border-gray-300 px-2 py-1.5 text-left font-semibold">Material</th>
            <th className="border-r border-gray-300 px-2 py-1.5 text-right font-semibold">Qty</th>
            <th className="border-r border-gray-300 px-2 py-1.5 text-left font-semibold">Unit</th>
            <th className="border-r border-gray-300 px-2 py-1.5 text-right font-semibold">Unit Cost</th>
            <th className="px-2 py-1.5 text-right font-semibold">Total</th>
          </tr>
        </thead>
        <tbody>
          {scrap.lines.map((line, i) => {
            const lineTotal = toNum(line.qty) * toNum(line.unitCost);
            return (
              <tr key={line.id} className="border-b border-gray-200">
                <td className="border-r border-gray-300 px-2 py-1.5 text-center">{i + 1}</td>
                <td className="border-r border-gray-300 px-2 py-1.5">
                  {line.material.name}
                  <span className="ml-1 text-xs text-gray-500">({line.material.code})</span>
                </td>
                <td className="border-r border-gray-300 px-2 py-1.5 text-right tnum">
                  {formatNumber(toNum(line.qty))}
                </td>
                <td className="border-r border-gray-300 px-2 py-1.5 text-center text-gray-600">
                  {line.material.unit}
                </td>
                <td className="border-r border-gray-300 px-2 py-1.5 text-right tnum">
                  {formatCurrency(toNum(line.unitCost))}
                </td>
                <td className="px-2 py-1.5 text-right tnum">{formatCurrency(lineTotal)}</td>
              </tr>
            );
          })}
        </tbody>
        <tfoot>
          <tr className="border-t border-gray-300">
            <td colSpan={2} className="px-2 py-1.5 text-right font-semibold">Total Qty:</td>
            <td className="px-2 py-1.5 text-right font-semibold tnum">{formatNumber(totalQty)}</td>
            <td colSpan={2} className="px-2 py-1.5 text-right font-semibold">Total Scrap Value:</td>
            <td className="px-2 py-1.5 text-right tnum">{formatCurrency(totalValue)}</td>
          </tr>
          <tr className="border-t-2 border-black">
            <td colSpan={5} className="px-2 py-2 text-right font-bold">Grand Total:</td>
            <td className="px-2 py-2 text-right font-bold tnum">{formatCurrency(totalValue)}</td>
          </tr>
        </tfoot>
      </table>

      {/* Notes */}
      {scrap.notes && (
        <div className="mt-3 text-sm">
          <span className="font-semibold">Notes: </span>
          <span>{scrap.notes}</span>
        </div>
      )}

      {/* Terms & Conditions */}
      <div className="mt-4 border-t border-gray-300 pt-2 text-xs text-gray-600">
        <div className="font-semibold text-gray-700">Notes:</div>
        <ol className="ml-4 list-decimal space-y-0.5">
          <li>This slip records internally generated scrap/by-product material added to stock.</li>
          <li>Scrap valuation is set at generation time and may differ from the original material cost.</li>
          <li>Stock has been updated at the destination location with the specified quantities.</li>
          <li>This is a computer-generated slip.</li>
        </ol>
      </div>

      {/* Signature blocks */}
      <div className="mt-10 grid grid-cols-2 gap-12 text-center text-sm">
        <div className="border-t border-black pt-1">Generated By</div>
        <div className="border-t border-black pt-1">For {company.name}</div>
      </div>

    </div>
    </>
  );
}
