import { chromium } from "playwright";
const BASE = "http://localhost:3000";
const UA = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1";
const browser = await chromium.launch();
const ctx = await browser.newContext({ userAgent: UA, viewport:{width:390,height:844}, isMobile:true, hasTouch:true });
const p = await ctx.newPage();
const res = await p.request.post(`${BASE}/api/auth/demo-login`, { data:{role:"OWNER"} });
const { email, password } = await res.json();
await p.request.post(`${BASE}/api/auth/sign-in/email`, { data:{email,password} });
await p.close();
const page = await ctx.newPage();
const errs=[];
page.on("console", m => { if(m.type()==="error") errs.push(m.text().slice(0,200)); });
page.on("response", async r => { if(r.status()>=400&&!r.url().includes("monitoring")) console.log("REQ",r.status(),r.url().split(BASE)[1]); });
await page.goto(`${BASE}/m/material-sales/new`, { waitUntil:"networkidle", timeout:120000 });
await page.waitForTimeout(5000);
console.log("HTML len:", await page.evaluate(()=>document.querySelector("main")?.innerHTML.length));
console.log("TEXT:", await page.evaluate(()=>document.querySelector("main")?.innerText.slice(0,400)));
console.log("ERRS:", JSON.stringify(errs.slice(0,5)));
await page.screenshot({path:"/tmp/msale.png"});
await browser.close();
