import { chromium } from "playwright";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { PrismaClient } = require("../packages/db/src/generated/prisma/client.js");
const prisma = new PrismaClient();
const BASE = "http://localhost:3000";
const UA = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1";
const STAMP = Date.now().toString(36).slice(-6).toUpperCase();
const browser = await chromium.launch();
const ctx = await browser.newContext({ userAgent: UA, viewport:{width:390,height:844}, isMobile:true, hasTouch:true });
const p = await ctx.newPage();
const res = await p.request.post(`${BASE}/api/auth/demo-login`, { data:{role:"SITE_ENGINEER"} });
const { email, password } = await res.json();
await p.request.post(`${BASE}/api/auth/sign-in/email`, { data:{email,password} });
await p.close();
const page = await ctx.newPage();
page.on("response", async r => { if(r.url().includes("/api/dprs")) console.log("DPR API", r.status(), (await r.text()).slice(0,150)); });
const project = await prisma.project.findFirst({ where:{ deletedAt:null } });
await page.goto(`${BASE}/m/site/dpr?project=${project.id}`, { waitUntil:"networkidle", timeout:120000 });
await page.waitForTimeout(2500);
await page.locator('main textarea[placeholder*="What work"]').fill(`QA ${STAMP} test`);
await page.getByRole("button",{name:/^Submit DPR$/i}).click();
await page.waitForTimeout(2500);
await page.getByRole("button",{name:/no.?work|submit anyway/i}).first().click();
await page.waitForTimeout(4000);
const d = await prisma.dailyProgressReport.findFirst({ where:{workSummary:{contains:STAMP}} });
console.log("ROW:", d ? `${d.dprNumber} ${d.status}` : "none");
await browser.close(); await prisma.$disconnect();
