import { chromium } from "playwright";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { PrismaClient } = require("../packages/db/src/generated/prisma/client.js");
const prisma = new PrismaClient();
const BASE = "http://localhost:3000";
const UA = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1";
const STAMP = Date.now().toString(36).slice(-6).toUpperCase();
const browser = await chromium.launch();
const ctx = await browser.newContext({ userAgent: UA, viewport:{width:390,height:844}, isMobile:true, hasTouch:true });
const p = await ctx.newPage();
const res = await p.request.post(`${BASE}/api/auth/demo-login`, { data:{role:"SITE_ENGINEER"} });
const { email, password } = await res.json();
await p.request.post(`${BASE}/api/auth/sign-in/email`, { data:{email,password} });
await p.close();
const page = await ctx.newPage();
page.on("response", async r => { if(r.url().includes("/api/expense-claims")) console.log("API", r.status(), (await r.text()).slice(0,200)); });
await page.goto(`${BASE}/m/expense-claims/new`, { waitUntil:"networkidle", timeout:120000 });
await page.waitForTimeout(3000);
await page.getByPlaceholder(/what is this claim/i).fill(`QA ${STAMP} diesel top-up`);
await page.getByPlaceholder(/e\.g\. Travel/i).fill("Fuel");
await page.getByPlaceholder("0").first().fill("1250");
await page.screenshot({path:"/tmp/claim-filled.png"});
const submit = page.getByRole("button",{name:/submit|create|save/i}).first();
console.log("submit visible:", await submit.isVisible().catch(()=>false), await submit.innerText().catch(()=>""));
await submit.click();
await page.waitForTimeout(5000);
console.log("AFTER:", (await page.evaluate(()=>document.body.innerText.slice(-400))));
await page.screenshot({path:"/tmp/claim-after.png"});
const c = await prisma.expenseClaim.findFirst({ orderBy:{createdAt:"desc"}, select:{id:true,status:true,totalAmount:true} });
console.log("LATEST CLAIM:", JSON.stringify(c));
await browser.close(); await prisma.$disconnect();
