/**
 * ═══════════════════════════════════════════════════════════════════
 * PAGE INVENTORY — every route in the app, for smoke testing.
 * ═══════════════════════════════════════════════════════════════════
 *
 * Generated from `find src/app -name page.tsx`. Dynamic segments
 * ([id]) are listed but skipped in smoke tests (no valid ID known
 * at generation time); they're covered by deep flow tests instead.
 */

export type PageEntry = {
  path: string;
  /** Optional: the expected <h1> title (for a stronger assertion). */
  title?: string;
  /** Skip in smoke tests (dynamic segment, auth-only, etc.) */
  skip?: boolean;
  /** Skip reason (for documentation). */
  skipReason?: string;
};

// ── Desktop pages (non-/m, non-/api, non-/print) ───────────────────
export const DESKTOP_PAGES: PageEntry[] = [
  { path: "/", title: "Today" },
  { path: "/build" },
  { path: "/me" },
  { path: "/my-tasks" },
  { path: "/tasks" },
  { path: "/approvals" },
  { path: "/calls" },
  { path: "/calls/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/reports" },
  { path: "/reports/calls" },
  { path: "/reports/balance-sheet" },
  { path: "/reports/cash-flow" },
  { path: "/reports/comparative" },
  { path: "/reports/department-consumption" },
  { path: "/reports/expenses" },
  { path: "/reports/gst" },
  { path: "/reports/inventory-value" },
  { path: "/reports/issue-register" },
  { path: "/reports/job-costing" },
  { path: "/reports/payroll-expense" },
  { path: "/reports/pending-payments" },
  { path: "/reports/profit" },
  { path: "/reports/project-progress" },
  { path: "/reports/purchase-register" },
  { path: "/reports/purchase-trends" },
  { path: "/reports/purchaser-performance" },
  { path: "/reports/real-estate-inventory" },
  { path: "/reports/sales-revenue" },
  { path: "/reports/stock-movement-summary" },
  { path: "/reports/tds-certificates" },
  // Acquire
  { path: "/land" },
  { path: "/land/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/suppliers" },
  { path: "/suppliers/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/vendor-ratings" },
  { path: "/rate-contracts" },
  // Procure
  { path: "/requisitions" },
  { path: "/quotations" },
  { path: "/quotations/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/procurement" },
  { path: "/procurement/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/field" },
  { path: "/supplier-returns" },
  // Stock
  { path: "/stock" },
  { path: "/stock-movements" },
  { path: "/materials" },
  { path: "/materials/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/equipment" },
  { path: "/gate-passes" },
  { path: "/standard-consumptions" },
  { path: "/material-reconciliation" },
  { path: "/departments" },
  { path: "/vehicles" },
  { path: "/transfers" },
  { path: "/stock-counts" },
  { path: "/scrap-generations" },
  { path: "/material-sales" },
  // Construct
  { path: "/projects" },
  { path: "/projects/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/boq" },
  { path: "/wbs" },
  { path: "/measurement-book" },
  { path: "/work-orders" },
  { path: "/change-orders" },
  { path: "/change-orders/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/subcontractors" },
  { path: "/project-control" },
  { path: "/budget-variance" },
  { path: "/profit-center" },
  { path: "/quality-control" },
  { path: "/quality-control/ncr/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/safety" },
  { path: "/safety/hazards/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/safety/incidents/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/renovations" },
  // Sell
  { path: "/customers" },
  { path: "/sales" },
  { path: "/sales/[id]/print", skip: true, skipReason: "dynamic id" },
  { path: "/rentals" },
  { path: "/rent" },
  { path: "/brokers" },
  { path: "/crm" },
  { path: "/portal-listings" },
  { path: "/portal" },
  { path: "/portal/login" },
  { path: "/units" },
  // People
  { path: "/hr" },
  { path: "/hr/attendance" },
  { path: "/hr/crews" },
  { path: "/hr/daily-reports" },
  { path: "/hr/dprs" },
  { path: "/hr/employees" },
  { path: "/hr/employees/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/hr/leaves" },
  { path: "/hr/payroll" },
  { path: "/hr/pending" },
  // Books
  { path: "/finance" },
  { path: "/finance/audit" },
  { path: "/finance/dpr-reconciliation" },
  { path: "/gl" },
  { path: "/expenses" },
  { path: "/expense-budgets" },
  { path: "/expense-claims" },
  { path: "/recurring-expenses" },
  { path: "/petty-cash" },
  { path: "/supplier-payments" },
  { path: "/health-books" },
  // Settings
  { path: "/settings" },
  { path: "/settings/backup" },
  { path: "/settings/project-assignments" },
  { path: "/permissions" },
  { path: "/telephony" },
  { path: "/sms" },
  { path: "/feedback" },
  { path: "/workflows" },
  { path: "/workflows/new" },
  { path: "/workflows/[id]", skip: true, skipReason: "dynamic id" },
  // Auth pages (no shell, different layout)
  { path: "/sign-in", skip: true, skipReason: "auth page — covered in auth flow" },
  { path: "/sign-up", skip: true, skipReason: "auth page — covered in auth flow" },
  { path: "/forgot-password", skip: true, skipReason: "auth page" },
  { path: "/reset-password", skip: true, skipReason: "auth page" },
  { path: "/change-password", skip: true, skipReason: "auth page" },
  { path: "/consent", skip: true, skipReason: "consent flow" },
];

// ── Mobile pages (/m/...) ──────────────────────────────────────────
export const MOBILE_PAGES: PageEntry[] = [
  { path: "/m" },
  { path: "/m/home" },
  { path: "/m/page" },
  { path: "/m/me" },
  { path: "/m/accounts" },
  { path: "/m/alerts/lease-expiry" },
  { path: "/m/attendance" },
  { path: "/m/books/finance" },
  { path: "/m/books/gl" },
  { path: "/m/books" },
  { path: "/m/books/payroll" },
  { path: "/m/books/receipts" },
  { path: "/m/books/receipts/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/books/reports" },
  { path: "/m/boq" },
  { path: "/m/boq/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/brokers" },
  { path: "/m/brokers/new" },
  { path: "/m/budget-variance" },
  { path: "/m/budget-variance/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/calls" },
  { path: "/m/calls/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/change-orders" },
  { path: "/m/change-orders/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/crm" },
  { path: "/m/customers" },
  { path: "/m/customers/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/customers/new" },
  { path: "/m/departments" },
  { path: "/m/dprs" },
  { path: "/m/dprs/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/equipment" },
  { path: "/m/equipment/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/equipment/new" },
  { path: "/m/expense-claims" },
  { path: "/m/expense-claims/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/expenses" },
  { path: "/m/gate-pass" },
  { path: "/m/hr" },
  { path: "/m/hr/employees" },
  { path: "/m/hr/employees/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/hr/leaves" },
  { path: "/m/hr/pending" },
  { path: "/m/inventory" },
  { path: "/m/land" },
  { path: "/m/land/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/leads" },
  { path: "/m/leads/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/leads/new" },
  { path: "/m/material-issues/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/material-reconciliation" },
  { path: "/m/material-sales" },
  { path: "/m/material-sales/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/material-sales/new" },
  { path: "/m/materials" },
  { path: "/m/materials/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/materials/[id]/edit", skip: true, skipReason: "dynamic id" },
  { path: "/m/materials/new" },
  { path: "/m/measurement-book" },
  { path: "/m/measurement-book/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/permissions" },
  { path: "/m/petty-cash" },
  { path: "/m/portal-listings" },
  { path: "/m/portal-listings/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/portal-listings/new" },
  { path: "/m/procurement" },
  { path: "/m/procurement/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/procurement/new" },
  { path: "/m/profit-center" },
  { path: "/m/project-control" },
  { path: "/m/project-control/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/projects" },
  { path: "/m/projects/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/pulse" },
  { path: "/m/pulse/approvals" },
  { path: "/m/pulse/attention" },
  { path: "/m/quality-control" },
  { path: "/m/quality-control/ncr/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/queue" },
  { path: "/m/quotations" },
  { path: "/m/quotations/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/quotations/new" },
  { path: "/m/rate-contracts" },
  { path: "/m/rate-contracts/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/rent" },
  { path: "/m/rentals" },
  { path: "/m/rentals/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/reports" },
  { path: "/m/reports/balance-sheet" },
  { path: "/m/reports/cash-flow" },
  { path: "/m/reports/comparative" },
  { path: "/m/reports/department-consumption" },
  { path: "/m/reports/expenses" },
  { path: "/m/reports/gst" },
  { path: "/m/reports/inventory-value" },
  { path: "/m/reports/issue-register" },
  { path: "/m/reports/job-costing" },
  { path: "/m/reports/payroll-expense" },
  { path: "/m/reports/pending-payments" },
  { path: "/m/reports/profit" },
  { path: "/m/reports/project-progress" },
  { path: "/m/reports/purchase-register" },
  { path: "/m/reports/purchase-trends" },
  { path: "/m/reports/purchaser-performance" },
  { path: "/m/reports/real-estate-inventory" },
  { path: "/m/reports/sales-revenue" },
  { path: "/m/reports/stock-movement-summary" },
  { path: "/m/reports/tds-certificates" },
  { path: "/m/requisitions" },
  { path: "/m/requisitions/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/requisitions/new" },
  { path: "/m/safety" },
  { path: "/m/safety/hazards/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/safety/incidents/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/safety/inspections/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/sales" },
  { path: "/m/sales/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/sales/new" },
  { path: "/m/scrap-generations" },
  { path: "/m/scrap-generations/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/scrap-generations/new" },
  { path: "/m/settings" },
  { path: "/m/settings/company" },
  { path: "/m/settings/export" },
  { path: "/m/settings/notifications" },
  { path: "/m/settings/project-assignments" },
  { path: "/m/settings/team" },
  { path: "/m/site" },
  { path: "/m/site/attendance" },
  { path: "/m/site/dpr" },
  { path: "/m/site/field" },
  { path: "/m/site/issue" },
  { path: "/m/site/me" },
  { path: "/m/site/receive" },
  { path: "/m/site/stock" },
  { path: "/m/site/tasks" },
  { path: "/m/sms" },
  { path: "/m/standard-consumptions" },
  { path: "/m/standard-consumptions/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/stock" },
  { path: "/m/stock/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/stock-counts" },
  { path: "/m/stock-counts/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/stock-counts/new" },
  { path: "/m/stock-locations" },
  { path: "/m/stock-locations/new" },
  { path: "/m/stock-out" },
  { path: "/m/subcontractors" },
  { path: "/m/subcontractors/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/subcontractors/new" },
  { path: "/m/supplier-payments" },
  { path: "/m/supplier-payments/new" },
  { path: "/m/supplier-returns" },
  { path: "/m/supplier-returns/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/supplier-returns/new" },
  { path: "/m/suppliers" },
  { path: "/m/suppliers/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/suppliers/new" },
  { path: "/m/telephony" },
  { path: "/m/transfers" },
  { path: "/m/transfers/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/transfers/new" },
  { path: "/m/units" },
  { path: "/m/units/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/vehicles" },
  { path: "/m/wbs" },
  { path: "/m/wbs/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/work-orders" },
  { path: "/m/work-orders/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/workflows" },
  { path: "/m/workflows/[id]", skip: true, skipReason: "dynamic id" },
  { path: "/m/workflows/new" },
];
